const RouteName = {
    SPLSH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    TAB_NAVIGATOR: "TabNavigator",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    HOME_TAB: 'Home',
    SURVEY_TAB: 'Survey',
    FAMILY_SURVEY_TAB: 'FamilySurvey',
    VILLAGE_SURVEY_TAB: 'VillageSurvey',
    FAMILY_SURVEY_EDIT_TAB: 'FamilyFormSurveyEdit',
    VILLAGE_SURVEY_EDIT_TAB: 'VillageFormSurveyEdit',
    FAMILY_LIST_TAB: 'FamilyFormList',
    VILLAGE_LIST_TAB: 'VillageFormList',
    CHECKOUT_TAB: 'Checkout',
    WALLETS_TAB: 'Wallets',
    PROFILE_TAB: 'Profile',
    SELECT_LANGUAGE: 'TranslationScreen',
    FORGOT_PASSWORD: 'ForgotPassword',
    CHAT_SCREEN: 'Chatscreen',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICTION_SCREEN: 'NotificationScreen',
    PAYMENT_SCREEN: 'PaymentScreen',
    PAYMENT_SUCCESSFULLY: 'PaymentSuccessFully',
    EDIT_PROFILE_SCREEN: 'EditProfileScreen',   
    AUDIO_CALL_SCREEN: 'AudioCallScreen',   
    ALL_SERVEY_SCREEN: 'AllServeyScreen',   
    ANALYTICS_SCREEN: 'AnalyaticsSurveyScreen',   
    THANK_YOU_SCREEN: 'ThankyouScreen',   
    MAP_SCREEN: 'MapScreen', 
    EDIT_LOCATION_SCREEN: 'EditLocationScreen', 
    VIEW_REPORT_SCREEN: 'ViewSurveyReportScreen',
    ADD_FAMILY_SCREEN: 'AddFamilyScreen',
    
}
export default RouteName;