import * as Yup from 'yup';
export const VillageFormInitialValues = () => ({
  
 District: null,
 Block:null,
 GramPanchayat:null,
 RevenueVillage:null,
 TotalHouseholds:null,
 MalePopulation:null,
 FemalePopulation:null,
 InternalVillageRoads:null,
 InternalVillageRoadsRequirement:null,
 InternalDrainsAvailable:null,
 DrainsProperlyFunctional:null,
 IsElectrified:null,
 StreetLightingAvailable:null,
 StreetLightingType:null,
 VillageConnectedToGP:null,
 LengthAllWeatherRoadToGP:null,
 GPConnectedToPWDOrHighway:null,
 LengthAllWeatherRoadToHighway:null,
 MenInMigration:null,
 WomenInMigration:null,
 MinorChildrenInMigration:null,
 DrinkingWaterSource:null,
 AllHouseholdsWithToilets:null,
 AnganwadiCentre:null,
 PrimarySchoolAvailable:null,
 SecondarySchoolWithin3km:null,
 SubHealthCentre:null,
 CommunityCentreAvailable:null,
 CommonShedForWSHG:null,
 PlaygroundAvailable:null,
 CommunityTanks:null,
 MobileNetworkCoverage:null,
 DigitalConnectivity:null,
 DryingYard:null,
 PDSAvailable:null,
 DistanceOfPDS:null,
 BankingPostOfficeNearby:null,
 WaterFromIrrigationProject:null,
 RepairOrNewDistributionCanalRequired:null,
 LengthOfDistributionCanal:null,
 FunctionalLiftIrrigation:null,
 ScopeOfNewLiftIrrigation:null,
 FunctionalCheckDams:null,
 ScopeOfNewCheckDams:null,
 FunctionalDistributionCanal:null,
 ScopeOfNewDistributionCanal:null,
 RespondentName:null,
 IdentityRole:null,
 SurveyProcess:null,
 RespondentMobile:null,
 MeetingPhotoPath:null,
 GeoLocation:null,
 EnumeratorName:null,
 SurveyDate:"2025-12-10T15:30:00",
 TotalPopulation:0,
 TotalPersonsInMigration:0
});

export const VillageFormValidationSchema = (props)=>{
    return Yup.object().shape({
  District: Yup.string().required('District is required'),
  Block: Yup.string().required('Block is required'),
  GramPanchayat: Yup.string().required('Gram Panchayat is required'),
  RevenueVillage: Yup.string().required('Revenue Village is required'),
  TotalHouseholds: Yup.number().typeError('Total Households must be a number').required('Total Households is required'),
  MalePopulation: Yup.number().typeError('Male Population must be a number').required('Male Population is required'),
  FemalePopulation: Yup.number().typeError('Female Population must be a number').required('Female Population is required'),
  InternalVillageRoadsRequirement: Yup.string().when('InternalVillageRoads', {
    is: false,
    then: schema => schema.required('Internal Village Roads Requirement is required'),
    otherwise: schema => schema.notRequired()
  }),
//   LengthAllWeatherRoadToGP: Yup.number().typeError('Length to GP must be a number').required('Length to GP is required'),
  LengthAllWeatherRoadToHighway: Yup.number().typeError('Length to Highway must be a number').required('Length to Highway is required'),
  DrinkingWaterSource: Yup.string().required('Drinking Water Source is required'),
//   DistanceOfPDS: Yup.number().typeError('Distance of PDS must be a number').required('Distance of PDS is required'),
//   LengthOfDistributionCanal: Yup.number().typeError('Length of Distribution Canal must be a number').required('Length of Distribution Canal is required'),
//   ScopeOfNewDistributionCanal: Yup.number().typeError('Scope of New Distribution Canal must be a number').required('Scope of New Distribution Canal is required'),
  RespondentName: Yup.string().required('Respondent Name is required'),
  IdentityRole: Yup.string().required('Identity / Role is required'),
  SurveyProcess: Yup.string().required('Survey Process is required'),
  RespondentMobile: Yup.string()
    .matches(/^\d{10}$/, 'Mobile Number must be 10 digits')
    .required('Respondent Mobile is required'),
//   SurveyDate: Yup.date().required('Survey Date is required'),
})};
